version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_COMMITER_CONTRACT_ADDRESS: ${VITE_COMMITER_CONTRACT_ADDRESS}
        VITE_TON_NETWORK: ${VITE_TON_NETWORK}
        VITE_API_ADDRESS: ${VITE_API_ADDRESS}
        VITE_MANIFEST_URL: ${VITE_MANIFEST_URL}
    ports:
      - "5173:5173"

  postgres:
    image: postgres:16
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stake_habit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stake_habit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stake_habit"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate
    networks:
      - stake_habit
    volumes:
      - ./tg-bot/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/stake_habit?sslmode=disable",
        "up",
      ]
    links:
      - postgres

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: ./Dockerfile
      args:
        COMMITMENT_LINK_PREFIX: ${COMMITMENT_LINK_PREFIX}
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    ports:
      - "5174:5174"
    networks:
      - stake_habit
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:

networks:
  stake_habit:
