version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5173:5173"

  postgres:
    image: postgres:16
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stake_habit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stake_habit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stake_habit"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: ./migrate/Dockerfile
    networks:
      - stake_habit
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/stake_habit?sslmode=disable",
        "up",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: ./Dockerfile
    ports:
      - "5174:5174"
    networks:
      - stake_habit
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/tg-bot"]

volumes:
  pgdata:

networks:
  stake_habit:
